project_id = "kita-bahagia"

[db]
major_version = 15

[functions.create-registration]
verify_jwt = false

[functions.midtrans-webhook]
verify_jwt = false

[functions.payment-status]
verify_jwt = false
