// SUMBER DATA KEGIATAN KITA BAHAGIA
// Untuk memperbarui agenda di Beranda, Jadwal, dan Pendaftaran, edit file ini saja.
window.KB_EVENTS = Object.freeze([
  {
    slug: "asa-raya-baduy",
    name: "Asa Raya Baduy",
    description: "Trip menjelajah dan edukasi di Baduy, sambil membangun koneksi yang bermakna.",
    category: "Komunitas",
    categoryKey: "komunitas",
    start: "2026-10-24T09:00:00+07:00",
    end: "2026-10-25T23:59:59+07:00",
    date: "24–25 Oktober 2026",
    dateDay: "24–25",
    dateMonth: "Okt 2026",
    time: "09.00–12.00 WIB",
    location: "Baduy, Banten",
    status: "Pendaftaran dibuka",
    statusKey: "open",
    capacity: "12 slot tersisa",
    price: 350000,
    image: "img/hero-relawan.webp",
    imageAlt: "Relawan Kita Bahagia dalam kegiatan bersama"
  },
  {
    slug: "blueventure-di-pulau-tidung",
    name: "Blueventure di Pulau Tidung",
    description: "Kegiatan bermain dan berkarya bersama anak-anak dengan pendekatan yang aman, hangat, dan menyenangkan.",
    category: "Anak-anak",
    categoryKey: "anak-anak",
    start: "2026-11-07T13:00:00+07:00",
    end: "2026-11-08T23:59:59+07:00",
    date: "7–8 November 2026",
    dateDay: "07–08",
    dateMonth: "Nov 2026",
    time: "13.00–15.30 WIB",
    location: "Pulau Tidung, Jakarta",
    status: "Pendaftaran dibuka",
    statusKey: "open",
    capacity: "8 slot tersisa",
    price: 425000,
    image: "img/hero-komunitas.webp",
    imageAlt: "Kebersamaan dalam kegiatan Kita Bahagia"
  },
  {
    slug: "bahagia-kasih",
    name: "Bahagia Kasih",
    description: "Workshop kreativitas ringan untuk berekspresi sambil memberi manfaat kepada masyarakat sekitar.",
    category: "Kreatif",
    categoryKey: "kreatif",
    start: "2026-11-22T10:00:00+07:00",
    end: "2026-11-22T23:59:59+07:00",
    date: "22 November 2026",
    dateDay: "22",
    dateMonth: "Nov 2026",
    time: "10.00–12.00 WIB",
    location: "Bandung",
    status: "Pendaftaran dibuka",
    statusKey: "open",
    capacity: "20 slot tersisa",
    price: 0,
    image: "img/hero-kebersamaan.webp",
    imageAlt: "Kegiatan sosial Kita Bahagia"
  },
  {
    slug: "bahagia-belajar-beraksi",
    name: "Bahagia Belajar & Beraksi",
    description: "Program kolaborasi untuk aksi sosial dan pembelajaran bersama di lingkungan sekitar.",
    category: "Lingkungan",
    categoryKey: "lingkungan",
    start: "2026-11-29T08:30:00+07:00",
    end: "2026-11-29T23:59:59+07:00",
    date: "29 November 2026",
    dateDay: "29",
    dateMonth: "Nov 2026",
    time: "08.30–11.30 WIB",
    location: "Bandung",
    status: "Pendaftaran dibuka",
    statusKey: "open",
    capacity: "20 slot tersisa",
    price: 150000,
    image: "img/hero-relawan.webp",
    imageAlt: "Relawan dalam kegiatan belajar dan aksi bersama"
  }
]);
